CREATE TABLE dbo.[ApplicationReview] (
    [Id]					        uniqueidentifier NOT NULL,
    [Ukprn]                         int NOT NULL,
    [AccountId]             bigint NOT NULL,
    [Owner]                         tinyint NOT NULL,
    [CandidateFeedback]             nvarchar(max) NULL,
    [CandidateId]                   uniqueidentifier not NULL,
    [CreatedDate]                   DATETIME NOT NULL,
    [DateSharedWithEmployer]        DATETIME NULL,
    [HasEverBeenEmployerInterviewing] BIT NOT NULL DEFAULT 0,
    [IsWithdrawn]                    BIT NOT NULL DEFAULT 0,
    [ReviewedDate]                   DATETIME NULL,   
    [SubmittedDate]                  DATETIME NOT NULL,   
    [Status]                        tinyint NOT NULL,
    [StatusUpdatedByUserId]         uniqueidentifier NULL,
    [StatusUpdatedBy]               tinyint NULL, -- To determine if updated by employer or provider,
    [VacancyReference]              BIGINT NOT NULL,
    [LegacyApplicationId]           uniqueidentifier NULL,
    CONSTRAINT [PK_ApplicationReview] PRIMARY KEY (Id),
    INDEX [IX_ApplicationReview_Ukprn] NONCLUSTERED(Ukprn, Owner),
    INDEX [IX_ApplicationReview_AccountId] NONCLUSTERED(AccountId, Owner),
    INDEX [IX_ApplicationReview_CandidateId] NONCLUSTERED(CandidateId),
    INDEX [IX_ApplicationReview_VacancyRef] NONCLUSTERED(VacancyReference)
)