CREATE TABLE dbo.[ApplicationReview] (
    [Id]					        uniqueidentifier	NOT NULL,
    [Ukprn]                         int NOT NULL,
    [AccountId]                     bigint NOT NULL,
    [AccountLegalEntityId]          bigint NOT NULL,
    [CandidateFeedback]             nvarchar(max) NULL,
    [EmployerFeedback]              nvarchar(max) NULL,
    [CandidateId]                   uniqueidentifier not NULL,
    [CreatedDate]                   DATETIME NOT NULL,
    [DateSharedWithEmployer]        DATETIME NULL,
    [HasEverBeenEmployerInterviewing] BIT NOT NULL DEFAULT 0,
    [WithdrawnDate]                 DATETIME NULL,
    [ReviewedDate]                  DATETIME NULL,   
    [SubmittedDate]                 DATETIME NULL,   
    [Status]                        NVARCHAR(50) NOT NULL,
    [TemporaryReviewStatus]         NVARCHAR(50) NULL,
    [StatusUpdatedDate]             DATETIME NULL,
    [VacancyReference]              BIGINT NOT NULL,
    [LegacyApplicationId]           uniqueidentifier NULL,
    [ApplicationId]                 uniqueidentifier NULL, --For V2 Applications
    [AdditionalQuestion1]           NVARCHAR(max) NULL,
    [AdditionalQuestion2]           NVARCHAR(max) NULL,
    [VacancyTitle]                  NVARCHAR(500) NOT NULL,
    CONSTRAINT [PK_ApplicationReview] PRIMARY KEY (Id),
    INDEX [IX_ApplicationReview_Ukprn] NONCLUSTERED(Ukprn),
    INDEX [IX_ApplicationReview_AccountId] NONCLUSTERED(AccountId),
    INDEX [IX_ApplicationReview_UkprnVacancyReference] NONCLUSTERED(Ukprn,VacancyReference),
    INDEX [IX_ApplicationReview_AccountIdVacancyReference] NONCLUSTERED(AccountId,VacancyReference),
    INDEX [IX_ApplicationReview_UkprnWithdrawnDate] NONCLUSTERED(Ukprn, WithdrawnDate),
    INDEX [IX_ApplicationReview_AccountIdWithdrawnDate] NONCLUSTERED(AccountId,WithdrawnDate),
    INDEX [IX_ApplicationReview_CandidateId] NONCLUSTERED(CandidateId),
    INDEX [IX_ApplicationReview_ApplicationId] NONCLUSTERED(ApplicationId),
    INDEX [IX_ApplicationReview_VacancyRef] NONCLUSTERED(VacancyReference),
    INDEX [IX_ApplicationReview_Status] NONCLUSTERED(Status),
    INDEX [IX_ApplicationReview_AccountId_DateSharedWithEmployer_Status_WithdrawnDate]  NONCLUSTERED([AccountId], [DateSharedWithEmployer])  INCLUDE ([Status], [WithdrawnDate]),
    INDEX [IX_ApplicationReviewEntities_Ukprn_Status_WithdrawnDate]  NONCLUSTERED(Ukprn, Status, WithdrawnDate)  INCLUDE (VacancyReference),
    INDEX [IX_ApplicationReview_Account_Status_Withdrawn] NONCLUSTERED(AccountId, Status, WithdrawnDate)  INCLUDE (VacancyReference),
    INDEX [IX_ApplicationReview_Ukprn_SubmittedDate] NONCLUSTERED(Ukprn, SubmittedDate)  INCLUDE (VacancyReference)
    )