CREATE TABLE dbo.[User] (
    [Id]	                                                        uniqueidentifier	NOT NULL,
    [IdamsUserId]                                                   nvarchar(200)       NULL,
    [DfEUserId]                                                     nvarchar(200)       NULL,
    [UserType]                                                      nvarchar(50)        NOT NULL,
    [CreatedDate]                                                   datetime            NOT NULL,
    [UpdatedDate]                                                   datetime            NULL,
    [LastSignedInDate]                                              datetime            NULL,
    [Name]                                                          nvarchar(500)       NOT NULL,
    [Email]                                                         nvarchar(255)       NOT NULL,
    [EmployerAccountIds]                                            nvarchar(max)       NOT NULL Default('[]'),
    [Ukprn]                                                         BIGINT              NULL,
    [TransferredVacanciesEmployerRevokedPermissionAlertDismissedOn] datetime            NULL,
    [ClosedVacanciesBlockedProviderAlertDismissedOn]                datetime            NULL,
    [TransferredVacanciesBlockedProviderAlertDismissedOn]           datetime            NULL,
    [ClosedVacanciesWithdrawnByQaAlertDismissedOn]                  datetime            NULL,
    CONSTRAINT [PK_User] PRIMARY KEY (Id),
    INDEX [IX_User_DfEUserId] NONCLUSTERED(DfEUserId),
    INDEX [IX_User_IdamsUserId] NONCLUSTERED(IdamsUserId)
)