CREATE TABLE dbo.[VacancyReview] (
    [Id]	                                    uniqueidentifier	NOT NULL,
    [VacancyReference]                          BIGINT              NOT NULL,
    [VacancyTitle]                              nvarchar(500)       NOT NULL,
    [CreatedDate]                               datetime            NOT NULL,
    [SlaDeadLine]                               datetime            NOT NULL,
    [ReviewedDate]                              datetime            NULL,
    [Status]                                    nvarchar(100)       NOT NULL,
    [SubmissionCount]                           tinyint             NOT NULL Default(1),
    [ReviewedByUserEmail]                       nvarchar(255)   	NULL,
    [SubmittedByUserEmail]                      nvarchar(255)	    NOT NULL,
    [ClosedDate]                                datetime            NULL,
    [ManualOutcome]                             nvarchar(50)        NULL,
    [ManualQaComment]                           nvarchar(max)       NULL,
    [ManualQaFieldIndicators]                   nvarchar(max)       NOT NULL Default('[]'),
    [AutomatedQaOutcome]                        nvarchar(max)       NULL,
    [AutomatedQaOutcomeIndicators]              nvarchar(20)        NULL,
    [DismissedAutomatedQAOutcomeIndicators]     nvarchar(max)       NOT NULL Default('[]'),
    [UpdatedFieldIdentifiers]                   nvarchar(max)       NOT NULL Default('[]'),
    [VacancySnapshot]                           nvarchar(max)       NOT NULL,
    [AccountId]                                 BIGINT              NOT NULL DEFAULT(0),
    [AccountLegalEntityId]                      BIGINT              NOT NULL DEFAULT(0),
    [Ukprn]                                     BIGINT              NOT NULL DEFAULT(0),
    [OwnerType]                                 tinyint             NOT NULL DEFAULT(3)
    CONSTRAINT [PK_VacancyReview] PRIMARY KEY (Id),
    INDEX [IX_VacancyReview_VacancyReference] NONCLUSTERED(VacancyReference),
    INDEX [IX_VacancyReview_VacancyReferenceStatus] NONCLUSTERED(VacancyReference,Status),
    INDEX [IX_VacancyReview_VacancyReferenceStatusOwnerOutcome] NONCLUSTERED(VacancyReference,Status, OwnerType, ManualOutcome),
    INDEX [IX_VacancyReview_AccountId] NONCLUSTERED(AccountId),
    INDEX [IX_VacancyReview_AccountLegalEntityId] NONCLUSTERED(AccountLegalEntityId),
    INDEX [IX_VacancyReview_Ukprn] NONCLUSTERED(Ukprn),
    INDEX [IX_VacancyReview_UkprnOwnerType] NONCLUSTERED(Ukprn,OwnerType,Status),
    INDEX [IX_VacancyReview_AccountIdOwnerType] NONCLUSTERED(AccountId,OwnerType,Status),
)