using SFA.DAS.Recruit.Api.Domain.Entities;
using SFA.DAS.Recruit.Api.Domain.Extensions;
using SFA.DAS.Recruit.Api.Domain.Models;

namespace SFA.DAS.Recruit.Api.Models.Mappers;

internal static class VacancyMapper
{
    public static VacancyEntity ToEntity(Vacancy vacancy)
    {
        return new VacancyEntity {
            AccountId = vacancy.AccountId,
            AccountLegalEntityId = vacancy.AccountLegalEntityId,
            AdditionalQuestion1 = vacancy.AdditionalQuestion1,
            AdditionalQuestion2 = vacancy.AdditionalQuestion2,
            AdditionalTrainingDescription = vacancy.AdditionalTrainingDescription,
            AnonymousReason = vacancy.AnonymousReason,
            ApplicationInstructions = vacancy.ApplicationInstructions,
            ApplicationMethod = vacancy.ApplicationMethod,
            ApplicationUrl = vacancy.ApplicationUrl,
            ApprenticeshipType = vacancy.ApprenticeshipType,
            ApprovedDate = vacancy.ApprovedDate,
            ClosedDate = vacancy.ClosedDate,
            ClosingDate = vacancy.ClosingDate,
            ClosureReason = vacancy.ClosureReason,
            ContactEmail = vacancy.Contact?.Email,
            ContactName = vacancy.Contact?.Name,
            ContactPhone = vacancy.Contact?.Phone,
            CreatedDate = vacancy.CreatedDate,
            DeletedDate = vacancy.DeletedDate,
            Description = vacancy.Description,
            DisabilityConfident = vacancy.DisabilityConfident,
            EmployerDescription = vacancy.EmployerDescription,
            EmployerLocationInformation = vacancy.EmployerLocationInformation,
            EmployerLocationOption = vacancy.EmployerLocationOption,
            EmployerLocations = ApiUtils.SerializeOrNull(vacancy.EmployerLocations),
            EmployerName = vacancy.EmployerName,
            EmployerNameOption = vacancy.EmployerNameOption,
            EmployerRejectedReason = vacancy.EmployerRejectedReason,
            EmployerReviewFieldIndicators = ApiUtils.SerializeOrNull(vacancy.EmployerReviewFieldIndicators),
            EmployerWebsiteUrl = vacancy.EmployerWebsiteUrl,
            GeoCodeMethod = vacancy.GeoCodeMethod,
            HasChosenProviderContactDetails = vacancy.HasChosenProviderContactDetails,
            HasOptedToAddQualifications = vacancy.HasOptedToAddQualifications,
            HasSubmittedAdditionalQuestions = vacancy.HasSubmittedAdditionalQuestions,
            Id = vacancy.Id,
            LastUpdatedDate = vacancy.LastUpdatedDate,
            LegalEntityName = vacancy.LegalEntityName,
            LiveDate = vacancy.LiveDate,
            NumberOfPositions = vacancy.NumberOfPositions,
            OutcomeDescription = vacancy.OutcomeDescription,
            OwnerType = vacancy.OwnerType,
            ProgrammeId = vacancy.ProgrammeId,
            ProviderReviewFieldIndicators = ApiUtils.SerializeOrNull(vacancy.ProviderReviewFieldIndicators),
            Qualifications = ApiUtils.SerializeOrNull(vacancy.Qualifications),
            ReviewCount = vacancy.ReviewCount,
            ReviewRequestedByUserId = vacancy.ReviewRequestedByUserId,
            ReviewRequestedDate = vacancy.ReviewRequestedDate,
            ShortDescription = vacancy.ShortDescription,
            Skills = ApiUtils.SerializeOrNull(vacancy.Skills),
            SourceOrigin = vacancy.SourceOrigin,
            SourceType = vacancy.SourceType,
            SourceVacancyReference = vacancy.SourceVacancyReference,
            StartDate = vacancy.StartDate,
            Status = vacancy.Status,
            SubmittedByUserId = vacancy.SubmittedByUserId,
            SubmittedDate = vacancy.SubmittedDate,
            ThingsToConsider = vacancy.ThingsToConsider,
            Title = vacancy.Title,
            TrainingDescription = vacancy.TrainingDescription,
            TrainingProvider_Address = ApiUtils.SerializeOrNull(vacancy.TrainingProvider?.Address),
            TrainingProvider_Name = vacancy.TrainingProvider?.Name,
            TransferInfo = ApiUtils.SerializeOrNull(vacancy.TransferInfo),
            Ukprn = (int?)vacancy.TrainingProvider?.Ukprn,
            VacancyReference = vacancy.VacancyReference,
            Wage_CompanyBenefitsInformation = vacancy.Wage?.CompanyBenefitsInformation,
            Wage_Duration = vacancy.Wage?.Duration,
            Wage_DurationUnit = vacancy.Wage?.DurationUnit,
            Wage_FixedWageYearlyAmount = vacancy.Wage?.FixedWageYearlyAmount,
            Wage_WageAdditionalInformation = vacancy.Wage?.WageAdditionalInformation,
            Wage_WageType = vacancy.Wage?.WageType,
            Wage_WeeklyHours = vacancy.Wage?.WeeklyHours,
            Wage_WorkingWeekDescription = vacancy.Wage?.WorkingWeekDescription
        };
    }

    public static Vacancy FromEntity(VacancyEntity vacancyEntity)
    {
        return new Vacancy {
            AccountId = vacancyEntity.AccountId,
            AccountLegalEntityId = vacancyEntity.AccountLegalEntityId,
            AdditionalQuestion1 = vacancyEntity.AdditionalQuestion1,
            AdditionalQuestion2 = vacancyEntity.AdditionalQuestion2,
            AdditionalTrainingDescription = vacancyEntity.AdditionalTrainingDescription,
            AnonymousReason = vacancyEntity.AnonymousReason,
            ApplicationInstructions = vacancyEntity.ApplicationInstructions,
            ApplicationMethod = vacancyEntity.ApplicationMethod,
            ApplicationUrl = vacancyEntity.ApplicationUrl,
            ApprenticeshipType = vacancyEntity.ApprenticeshipType,
            ApprovedDate = vacancyEntity.ApprovedDate,
            ClosedDate = vacancyEntity.ClosedDate,
            ClosingDate = vacancyEntity.ClosingDate,
            ClosureReason = vacancyEntity.ClosureReason,
            Contact = vacancyEntity.ContactEmail is null ? null : new ContactDetail()
            {
                Email = vacancyEntity.ContactEmail,
                Name = vacancyEntity.ContactName!,
                Phone = vacancyEntity.ContactPhone!,
            },
            CreatedDate = vacancyEntity.CreatedDate,
            DeletedDate = vacancyEntity.DeletedDate,
            Description = vacancyEntity.Description,
            DisabilityConfident = vacancyEntity.DisabilityConfident,
            EmployerDescription = vacancyEntity.EmployerDescription,
            EmployerLocationInformation = vacancyEntity.EmployerLocationInformation,
            EmployerLocationOption = vacancyEntity.EmployerLocationOption,
            EmployerLocations = ApiUtils.DeserializeOrNull<List<Models.Address>>(vacancyEntity.EmployerLocations),
            EmployerName = vacancyEntity.EmployerName,
            EmployerNameOption = vacancyEntity.EmployerNameOption,
            EmployerRejectedReason = vacancyEntity.EmployerRejectedReason,
            EmployerReviewFieldIndicators = ApiUtils.DeserializeOrNull<List<ReviewFieldIndicator>>(vacancyEntity.EmployerReviewFieldIndicators),
            EmployerWebsiteUrl = vacancyEntity.EmployerWebsiteUrl,
            GeoCodeMethod = vacancyEntity.GeoCodeMethod,
            HasChosenProviderContactDetails = vacancyEntity.HasChosenProviderContactDetails,
            HasOptedToAddQualifications = vacancyEntity.HasOptedToAddQualifications,
            HasSubmittedAdditionalQuestions = vacancyEntity.HasSubmittedAdditionalQuestions,
            Id = vacancyEntity.Id,
            LastUpdatedDate = vacancyEntity.LastUpdatedDate,
            LegalEntityName = vacancyEntity.LegalEntityName,
            LiveDate = vacancyEntity.LiveDate,
            NumberOfPositions = vacancyEntity.NumberOfPositions,
            OutcomeDescription = vacancyEntity.OutcomeDescription,
            OwnerType = vacancyEntity.OwnerType,
            ProgrammeId = vacancyEntity.ProgrammeId,
            ProviderReviewFieldIndicators = ApiUtils.DeserializeOrNull<List<ReviewFieldIndicator>>(vacancyEntity.ProviderReviewFieldIndicators),
            Qualifications = ApiUtils.DeserializeOrNull<List<Qualification>>(vacancyEntity.Qualifications),
            ReviewCount = vacancyEntity.ReviewCount,
            ReviewRequestedByUserId = vacancyEntity.ReviewRequestedByUserId,
            ReviewRequestedDate = vacancyEntity.ReviewRequestedDate,
            ShortDescription = vacancyEntity.ShortDescription,
            Skills = ApiUtils.DeserializeOrNull<List<string>>(vacancyEntity.Skills),
            SourceOrigin = vacancyEntity.SourceOrigin,
            SourceType = vacancyEntity.SourceType,
            SourceVacancyReference = vacancyEntity.SourceVacancyReference,
            StartDate = vacancyEntity.StartDate,
            Status = vacancyEntity.Status,
            SubmittedByUserId = vacancyEntity.SubmittedByUserId,
            SubmittedDate = vacancyEntity.SubmittedDate,
            ThingsToConsider = vacancyEntity.ThingsToConsider,
            Title = vacancyEntity.Title,
            TrainingDescription = vacancyEntity.TrainingDescription,
            TrainingProvider = vacancyEntity.Ukprn is null ? null :  new TrainingProvider
            {
                Ukprn = vacancyEntity.Ukprn,
                Name = vacancyEntity.TrainingProvider_Name!,
                Address = ApiUtils.DeserializeOrNull<TrainingProviderAddress>(vacancyEntity.TrainingProvider_Address)!,
            },
            TransferInfo = ApiUtils.DeserializeOrNull<TransferInfo>(vacancyEntity.TransferInfo),
            VacancyReference = vacancyEntity.VacancyReference,
            Wage = vacancyEntity.Wage_WageType is null ? null : new Wage
            {
                CompanyBenefitsInformation = vacancyEntity.Wage_CompanyBenefitsInformation,
                Duration = vacancyEntity.Wage_Duration,
                DurationUnit = vacancyEntity.Wage_DurationUnit,
                FixedWageYearlyAmount = vacancyEntity.Wage_FixedWageYearlyAmount,
                WageAdditionalInformation = vacancyEntity.Wage_WageAdditionalInformation,
                WageType = vacancyEntity.Wage_WageType,
                WeeklyHours = vacancyEntity.Wage_WeeklyHours,
                WorkingWeekDescription = vacancyEntity.Wage_WorkingWeekDescription,
            },
        };
    }
}